### ISSUE TITLE
Document deciders.py

### ISSUE THREAD

**Issue by latasianguy** [neurodata/ProgLearn#158]
Writing documentation for [deciders.py](https://github.com/neurodata/progressive-learning/blob/master/proglearn/deciders.py). Part of issue #4 . Code in progress [here](https://github.com/latasianguy/progressive-learning/blob/documentation-deciders.py/proglearn/deciders.py).

**Comment by levinwil** [comment]
@latasianguy How has progress been on this? Looking at the code on your branch, it seems like the Documentation for SimpleArgmaxAverage is basically done. Do you think you could switch that documentation over to the version on main and adapt it?

**Comment by latasianguy** [comment]
@levinwil new branch [here](https://github.com/latasianguy/progressive-learning/tree/document-deciders.py-new), let me know if I need to change anything before the PR, I'll close the other branch after the PR

**Comment by levinwil** [comment]
1. Parameters means parameters to the init function. _is_fitted is NOT one of those parameters 
2. Class attributes means variables that are internally saved. This DOES include _is_fitted
3. There are still some mentioned of ‘SimpleAverage’ instead of ‘ SimpleArgmaxAverage’

**Comment by levinwil** [comment]
You also don’t really need to mention anything about class attributes, since there aren’t any - just object attributes. 

You should also have method signatures in the unit docstring. See https://github.com/latasianguy/progressive-learning/blob/document-deciders.py-new/proglearn/voters.py for examples of this. 

Return statements in the doc strings should mention the types of the variables that are being returned

**Comment by levinwil** [comment]
Hey, @latasianguy do you have a progress report on this? We're in the process of generating documentation and this is the last major piece of documentation that we'd like to have finished.

**Comment by levinwil** [comment]
Closed per PR #280
